# Generated by Django 5.1.3 on 2024-11-20 06:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_for', models.CharField(choices=[('Producer', 'Producer'), ('Consumer', 'Consumer'), ('Recycler', 'Recycler'), ('Collector', 'Collector')], max_length=10)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('applicant_designation', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('-', 'Rather not say')], max_length=100)),
                ('cnic', models.CharField(help_text='XXXXX-XXXXXXX-X', max_length=15, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.RegexValidator(message='CNIC must be in the format XXXXX-XXXXXXX-X.', regex='^\\d{5}-\\d{7}-\\d{1}$')])),
                ('email', models.EmailField(max_length=255)),
                ('mobile_operator', models.CharField(choices=[('jazz', 'Mobilink'), ('telenor', 'Telenor'), ('ufone', 'Ufone'), ('warid', 'Warid')], max_length=15)),
                ('mobile_no', models.CharField(help_text='3001234567', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message="Mobile number must be exactly 10 digits, e.g., '3001234567'.", regex='^\\d{10}$')])),
                ('application_status', models.CharField(choices=[('Created', 'Created'), ('Submitted', 'Submitted'), ('In Review', 'In Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Process', 'In Process'), ('Completed', 'Completed')], default='Created', max_length=20)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
