# Generated by Django 5.1.3 on 2024-11-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0002_tbldistricts_tbldivisions_tbltehsils_byproducts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='single_use_plastic_items',
            field=models.ManyToManyField(to='pmc_api.plasticitems'),
        ),
    ]
