# Generated by Django 5.1.3 on 2024-11-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0003_alter_producer_single_use_plastic_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetail',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather not say', 'Rather not say')], max_length=100),
        ),
        migrations.AlterField(
            model_name='applicantdetail',
            name='mobile_operator',
            field=models.CharField(choices=[('Mobilink', 'Mobilink'), ('Telenor', 'Telenor'), ('Ufone', 'Ufone'), ('Warid', 'Warid')], max_length=15),
        ),
        migrations.AlterField(
            model_name='applicantdetail',
            name='registration_for',
            field=models.CharField(choices=[('Producer', 'Producer'), ('Consumer', 'Consumer'), ('Recycler', 'Recycler'), ('Collector', 'Collector')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='mobile_operator',
            field=models.CharField(choices=[('Mobilink', 'Mobilink'), ('Telenor', 'Telenor'), ('Ufone', 'Ufone'), ('Warid', 'Warid')], max_length=15),
        ),
        migrations.AlterField(
            model_name='producer',
            name='total_capacity_unit',
            field=models.CharField(blank=True, choices=[('kg_per_day', 'Kg/day'), ('ton_per_day', 'Ton/day')], max_length=255, null=True),
        ),
    ]
