# Generated by Django 5.1.3 on 2024-11-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0004_alter_applicantdetail_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetail',
            name='tracking_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
