# Generated by Django 5.1.3 on 2024-11-26 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0007_remove_businessprofile_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='is_carry_bags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producer',
            name='is_plastic_packing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producer',
            name='is_single_use_plastics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='applicant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businessprofile', to='pmc_api.applicantdetail'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='is_waste_disposal_provision',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='is_waste_storage_capacity',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
