# Generated by Django 5.1.3 on 2024-11-30 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0009_alter_producer_tracking_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetail',
            name='assigned_group',
            field=models.CharField(choices=[('USER', 'USER'), ('LSO', 'LSO'), ('LSM', 'LSM'), ('DO', 'DO'), ('TL', 'TL'), ('MO', 'MO')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ApplicationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_group', models.CharField(choices=[('USER', 'USER'), ('LSO', 'LSO'), ('LSM', 'LSM'), ('DO', 'DO'), ('TL', 'TL'), ('MO', 'MO')], max_length=100, null=True)),
                ('remarks', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmc_api.applicantdetail')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationassignmentcreatedby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationassignmentupdatedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
