# Generated by Django 5.1.3 on 2024-11-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0010_applicantdetail_assigned_group_applicationassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationassignment',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
