# Generated by Django 5.1.3 on 2024-12-05 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0011_alter_applicationassignment_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='district',
            field=models.ForeignKey(blank=True, db_column='district_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='pmc_api.tbldistricts', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='tehsil',
            field=models.ForeignKey(blank=True, db_column='tehsil_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='pmc_api.tbltehsils', verbose_name='Tehsil'),
        ),
        migrations.AlterField(
            model_name='applicantdetail',
            name='assigned_group',
            field=models.CharField(choices=[('APPLICANT', 'APPLICANT'), ('LSO', 'LSO'), ('LSM', 'LSM'), ('DO', 'DO'), ('LSM2', 'LSM2'), ('TL', 'TL'), ('DEO', 'DEO'), ('Download License', 'Download License')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationassignment',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicationassignment', to='pmc_api.applicantdetail'),
        ),
        migrations.AlterField(
            model_name='applicationassignment',
            name='assigned_group',
            field=models.CharField(choices=[('APPLICANT', 'APPLICANT'), ('LSO', 'LSO'), ('LSM', 'LSM'), ('DO', 'DO'), ('LSM2', 'LSM2'), ('TL', 'TL'), ('DEO', 'DEO'), ('Download License', 'Download License')], max_length=100, null=True),
        ),
    ]
