# Generated by Django 5.1.3 on 2024-12-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0012_businessprofile_district_businessprofile_tehsil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetail',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetail',
            name='mobile_operator',
            field=models.CharField(blank=True, choices=[('Mobilink', 'Mobilink'), ('Telenor', 'Telenor'), ('Ufone', 'Ufone'), ('Warid', 'Warid')], max_length=15, null=True),
        ),
    ]
