# Generated by Django 5.1.3 on 2024-12-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0013_alter_applicantdetail_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
