# Generated by Django 5.1.3 on 2024-12-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0008_alter_producer_action_plan_and_more'),
        ('pmc_api', '0014_alter_businessprofile_email'),
    ]

    operations = [
    ]
