# Generated by Django 5.1.3 on 2024-12-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0015_merge_20241208_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetail',
            name='assigned_group',
            field=models.CharField(choices=[('LSO', 'LSO'), ('LSM', 'LSM'), ('DO', 'DO'), ('LSM2', 'LSM'), ('TL', 'TL'), ('DEO', 'DEO'), ('Download License', 'Download License')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationassignment',
            name='assigned_group',
            field=models.CharField(choices=[('LSO', 'LSO'), ('LSM', 'LSM'), ('DO', 'DO'), ('LSM2', 'LSM'), ('TL', 'TL'), ('DEO', 'DEO'), ('Download License', 'Download License')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='action_plan',
            field=models.FileField(blank=True, null=True, upload_to='action_plan/'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='consent_permit',
            field=models.FileField(blank=True, null=True, upload_to='permit/'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='flow_diagram',
            field=models.FileField(blank=True, null=True, upload_to='diagrams/'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='personnel_or_consumers_list',
            field=models.FileField(blank=True, null=True, upload_to='consumers/'),
        ),
        migrations.AlterField(
            model_name='recycler',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='labor_dept/'),
        ),
    ]
