# Generated by Django 5.1.3 on 2024-12-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0016_alter_applicantdetail_assigned_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='registration_number',
            new_name='number_of_machines',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='action_plan',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='by_products_list',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='consent_permit',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='date_of_commencement_of_production',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='flow_diagram',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='is_carry_bags',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='is_compliance_with_rules',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='is_plastic_packing',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='is_single_use_plastics',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='is_waste_disposal_provision',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='is_waste_storage_capacity',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='personnel_or_consumers_list',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='products_list',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='single_use_plastic_items',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='total_capacity_unit',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='total_waste_generated_unit',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='valid_consent_permit',
        ),
        migrations.AddField(
            model_name='producer',
            name='has_waste_storage_capacity',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='packaging_items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='plain_plastic_sheets_for_food_wrapping',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='waste_disposal_provision',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='registration_required_for',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
