# Generated by Django 5.1.3 on 2024-12-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0017_rename_registration_number_producer_number_of_machines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetail',
            name='applicant_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
