# Generated by Django 5.1.3 on 2024-12-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0018_alter_applicantdetail_applicant_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
