# Generated by Django 5.1.3 on 2024-12-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0020_alter_producer_has_waste_storage_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='registration_required_for_other',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
