# Generated by Django 5.1.3 on 2024-12-11 05:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0022_applicantdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetail',
            name='tracking_hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='applicantdetail',
            name='application_status',
            field=models.CharField(choices=[('Created', 'Created'), ('Fee Challan', 'Fee Challan'), ('Submitted', 'Submitted'), ('In Review', 'In Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Process', 'In Process'), ('Completed', 'Completed')], default='Created', max_length=20),
        ),
    ]
