# Generated by Django 5.1.3 on 2024-12-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0023_applicantdetail_tracking_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycler',
            name='business_commencement_date',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='impact_on_environment',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='is_labor_department_reg',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='no_of_workers',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='plastic_waste_acquired',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='pollution_control_detail',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='pollution_control_system',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='products_and_capacity',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='registration_certificate',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='safety_and_health_aspects',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='waste_disposal_details',
        ),
        migrations.RemoveField(
            model_name='recycler',
            name='waste_generated',
        ),
        migrations.AddField(
            model_name='recycler',
            name='has_adequate_pollution_control_systems',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='recycler',
            name='plastic_waste_acquired_through',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recycler',
            name='pollution_control_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recycler',
            name='selected_categories',
            field=models.JSONField(default=list),
        ),
    ]
