# Generated by Django 5.1.3 on 2024-12-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0024_remove_recycler_business_commencement_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='annual_consumption_weight_unit',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='annual_consumption_weight_val',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='annual_procurement_weight_unit',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='annual_procurement_weight_val',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='license_no_collector',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='license_no_recycler',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='no_of_disposal_bins',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='primary_plastics',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='registered_collector',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='registered_recycler',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='segregation_at_source',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='waste_disposal_bins',
        ),
        migrations.AddField(
            model_name='consumer',
            name='consumption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='no_of_waste_disposable_bins',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='packaging_items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='plain_plastic_sheets_for_food_wrapping',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='provision_waste_disposal_bins',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='consumer',
            name='registration_required_for',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consumer',
            name='registration_required_for_other',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consumer',
            name='segregated_plastics_handed_over_to_registered_recyclers',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
