# Generated by Django 5.1.3 on 2024-12-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0025_remove_consumer_annual_consumption_weight_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='average_annual_collection_unit',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='average_annual_collection_val',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='collection_persons',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='collection_source',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='collection_vehicles',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='disposal_source',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='collector',
            name='number_of_persons',
            field=models.PositiveIntegerField(blank=True, help_text='Number of persons for collection', null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='number_of_vehicles',
            field=models.PositiveIntegerField(blank=True, help_text='Number of vehicles for collection', null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='registration_required_for',
            field=models.JSONField(blank=True, help_text="Categories of Single Use Plastics (e.g., ['Carry bags', 'Packaging except food'])", null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='registration_required_for_other',
            field=models.JSONField(blank=True, help_text="Categories for Other Plastics (e.g., ['Plastic Utensils', 'PET Bottles'])", null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='selected_categories',
            field=models.JSONField(blank=True, help_text="Source of Disposal, with details for each category. Example: [{'category': 'Recycler', 'address': '123 Street Name'}, {'category': 'Landfill Site', 'address': '456 Another St'}]", null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='total_capacity_value',
            field=models.FloatField(blank=True, help_text='Collection in Kg per day', null=True),
        ),
    ]
