# Generated by Django 5.1.3 on 2024-12-12 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0026_remove_collector_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='applicant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmc_api.applicantdetail'),
        ),
    ]
