# Generated by Django 5.1.4 on 2024-12-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0027_collector_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='registration_required_for_other_other_text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='registration_required_for_other_other_text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='registration_required_for_other_other_text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
