# Generated by Django 5.1.4 on 2024-12-15 12:21

import pmc_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0028_collector_registration_required_for_other_other_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetail',
            name='tracking_hash',
            field=models.CharField(default=pmc_api.models.default_value_uuid, editable=False, max_length=36),
        ),
    ]
