# Generated by Django 5.1.4 on 2024-12-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0029_alter_applicantdetail_tracking_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycler',
            name='registration_required_for_other_other_text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
