# Generated by Django 5.1.4 on 2024-12-17 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0030_recycler_registration_required_for_other_other_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businessprofilecreatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collector',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectorcreatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumercreatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recycler',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recyclercreatedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
