# Generated by Django 5.1.3 on 2024-12-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0030_recycler_registration_required_for_other_other_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_number', models.CharField(max_length=17, unique=True)),
                ('psid_status', models.CharField(choices=[('PAID', 'PAID')], default='PAID', max_length=4)),
                ('dept_transaction_id', models.CharField(max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_date', models.DateField()),
                ('paid_time', models.TimeField()),
                ('bank_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'payment_intimation',
            },
        ),
    ]
