# Generated by Django 5.1.3 on 2024-12-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0031_paymentintimation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSIDTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_transaction_id', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('amount_within_due_date', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_after_due_date', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consumer_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('cnic', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('district_id', models.IntegerField()),
                ('amount_bifurcation', models.JSONField()),
                ('consumer_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='PSID')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
