# Generated by Django 5.1.4 on 2024-12-19 04:13

import pmc_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0031_businessprofile_created_by_collector_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocuments',
            name='document',
            field=models.FileField(upload_to=pmc_api.models.upload_to_with_uuid),
        ),
    ]
