# Generated by Django 5.1.4 on 2024-12-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0031_businessprofile_created_by_collector_created_by_and_more'),
        ('pmc_api', '0032_psidtracking'),
    ]

    operations = [
    ]
