# Generated by Django 5.1.4 on 2024-12-19 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0033_merge_20241218_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSubmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submittedapplication', to='pmc_api.applicantdetail')),
            ],
        ),
    ]
