# Generated by Django 5.1.4 on 2024-12-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0034_applicationsubmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetail',
            name='assigned_group',
            field=models.CharField(choices=[('APPLICANT', 'APPLICANT'), ('LSO', 'LSO'), ('LSM', 'LSM'), ('DO', 'DO'), ('LSM2', 'LSM'), ('TL', 'TL'), ('DEO', 'DEO'), ('Download License', 'Download License')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationassignment',
            name='assigned_group',
            field=models.CharField(choices=[('APPLICANT', 'APPLICANT'), ('LSO', 'LSO'), ('LSM', 'LSM'), ('DO', 'DO'), ('LSM2', 'LSM'), ('TL', 'TL'), ('DEO', 'DEO'), ('Download License', 'Download License')], max_length=100, null=True),
        ),
    ]
