# Generated by Django 5.1.4 on 2024-12-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0032_alter_applicantdocuments_document'),
        ('pmc_api', '0035_alter_applicantdetail_assigned_group_and_more'),
    ]

    operations = [
    ]
