# Generated by Django 5.1.3 on 2024-12-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0036_merge_20241219_2306'),
        ('pmc_api', '0036_merge_20241220_1452'),
    ]

    operations = [
    ]
