# Generated by Django 5.1.3 on 2024-12-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0037_merge_20241221_1023'),
        ('pmc_api', '0038_alter_applicantfieldresponse_created_by'),
    ]

    operations = [
    ]
