# Generated by Django 5.1.4 on 2024-12-26 03:20

import django.db.models.deletion
import pmc_api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0038_alter_applicantfieldresponse_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantManualFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('list_of_products', models.TextField(blank=True, null=True)),
                ('list_of_by_products', models.TextField(blank=True, null=True)),
                ('raw_material_imported', models.TextField(blank=True, null=True)),
                ('seller_name_if_raw_material_bought', models.CharField(blank=True, max_length=255, null=True)),
                ('self_import_details', models.TextField(blank=True, null=True)),
                ('raw_material_utilized', models.TextField(blank=True, null=True)),
                ('compliance_thickness_75', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('valid_consent_permit_building_bylaws', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('consent_permit_file', models.FileField(blank=True, null=True, upload_to=pmc_api.models.upload_to_with_uuid)),
                ('flow_diagram_file', models.FileField(blank=True, null=True, upload_to=pmc_api.models.upload_to_with_uuid)),
                ('action_plan_file', models.FileField(blank=True, null=True, upload_to=pmc_api.models.upload_to_with_uuid)),
                ('stockist_distributor_list', models.TextField(blank=True, null=True)),
                ('procurement_per_day', models.CharField(blank=True, help_text='Procurement in Kg per day', max_length=100, null=True)),
                ('no_of_workers', models.PositiveIntegerField(blank=True, null=True)),
                ('labor_dept_registration_status', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('occupational_safety_and_health_facilities', models.TextField(blank=True, null=True)),
                ('adverse_environmental_impacts', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_fields', to='pmc_api.applicantdetail')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicantmanualfields_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicantmanualfields_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
