# Generated by Django 5.1.4 on 2024-12-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0039_applicantmanualfields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantmanualfields',
            name='action_plan_file',
        ),
        migrations.RemoveField(
            model_name='applicantmanualfields',
            name='consent_permit_file',
        ),
        migrations.RemoveField(
            model_name='applicantmanualfields',
            name='flow_diagram_file',
        ),
    ]
