# Generated by Django 5.1.3 on 2024-12-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0039_merge_20241223_2012'),
        ('pmc_api', '0040_remove_applicantmanualfields_action_plan_file_and_more'),
    ]

    operations = [
    ]
