# Generated by Django 5.1.4 on 2024-12-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0040_remove_applicantmanualfields_action_plan_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicantfees', to='pmc_api.applicantdetail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
