# Generated by Django 5.1.4 on 2024-12-29 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0041_applicantfee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantfee',
            options={},
        ),
        migrations.AddIndex(
            model_name='applicantdetail',
            index=models.Index(fields=['application_status'], name='idx_app_status'),
        ),
        migrations.AddIndex(
            model_name='applicantdetail',
            index=models.Index(fields=['assigned_group'], name='idx_assigned_group'),
        ),
        migrations.AddIndex(
            model_name='applicantdetail',
            index=models.Index(fields=['created_by'], name='idx_created_by'),
        ),
        migrations.AddIndex(
            model_name='applicantdetail',
            index=models.Index(fields=['tracking_number'], name='idx_tracking_number'),
        ),
        migrations.AddIndex(
            model_name='applicantdetail',
            index=models.Index(fields=['application_status', 'assigned_group'], name='idx_status_group'),
        ),
        migrations.AddIndex(
            model_name='applicantdocuments',
            index=models.Index(fields=['applicant'], name='idx_document_applicant'),
        ),
        migrations.AddIndex(
            model_name='applicantdocuments',
            index=models.Index(fields=['created_by'], name='idx_document_created_by'),
        ),
        migrations.AddIndex(
            model_name='applicantfee',
            index=models.Index(fields=['applicant'], name='idx_fee_applicant'),
        ),
        migrations.AddIndex(
            model_name='applicantfee',
            index=models.Index(fields=['is_settled'], name='idx_fee_is_settled'),
        ),
        migrations.AddIndex(
            model_name='applicationassignment',
            index=models.Index(fields=['applicant'], name='idx_applicant_assignment'),
        ),
        migrations.AddIndex(
            model_name='applicationassignment',
            index=models.Index(fields=['assigned_group'], name='idx_assigned_group_assignment'),
        ),
        migrations.AddIndex(
            model_name='applicationassignment',
            index=models.Index(fields=['assigned_group', 'created_by'], name='idx_group_created_assignment'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['district'], name='idx_district'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['tehsil'], name='idx_tehsil'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['tracking_number'], name='idx_bp_tracking_number'),
        ),
        migrations.AddIndex(
            model_name='paymentintimation',
            index=models.Index(fields=['consumer_number'], name='idx_payment_consumer_number'),
        ),
        migrations.AddIndex(
            model_name='paymentintimation',
            index=models.Index(fields=['dept_transaction_id'], name='idx_payment_transaction_id'),
        ),
    ]
