# Generated by Django 5.1.3 on 2024-12-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0041_applicantfee'),
        ('pmc_api', '0041_merge_20241226_1426'),
    ]

    operations = [
    ]
