# Generated by Django 5.1.3 on 2024-12-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0042_alter_applicantfee_options_and_more'),
        ('pmc_api', '0042_merge_0041_applicantfee_0041_merge_20241226_1426'),
    ]

    operations = [
    ]
