# Generated by Django 5.1.4 on 2025-01-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0042_alter_applicantfee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=500)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalServiceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('access_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='Base endpoint of the service')),
                ('auth_endpoint', models.URLField(help_text='Authentication endpoint')),
                ('generate_psid_endpoint', models.URLField(help_text='PSID generation endpoint')),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='applicantdetail',
            name='assigned_group',
            field=models.CharField(choices=[('APPLICANT', 'APPLICANT'), ('LSO', 'LSO'), ('LSO1', 'LSO1'), ('LSO2', 'LSO2'), ('LSO3', 'LSO3'), ('LSM', 'LSM'), ('DO', 'DO'), ('LSM2', 'LSM'), ('TL', 'TL'), ('DEO', 'DEO'), ('Download License', 'Download License')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationassignment',
            name='assigned_group',
            field=models.CharField(choices=[('APPLICANT', 'APPLICANT'), ('LSO', 'LSO'), ('LSO1', 'LSO1'), ('LSO2', 'LSO2'), ('LSO3', 'LSO3'), ('LSM', 'LSM'), ('DO', 'DO'), ('LSM2', 'LSM'), ('TL', 'TL'), ('DEO', 'DEO'), ('Download License', 'Download License')], max_length=100, null=True),
        ),
    ]
