# Generated by Django 5.1.4 on 2025-01-02 11:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0043_apilog_externalservicetoken_serviceconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintimation',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psid_intimation', to='pmc_api.applicantdetail'),
        ),
        migrations.AddField(
            model_name='paymentintimation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paymentintimation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='psidtracking',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psid_tracking', to='pmc_api.applicantdetail'),
        ),
        migrations.AddField(
            model_name='psidtracking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentintimation',
            name='consumer_number',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='psidtracking',
            name='consumer_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='psidtracking',
            name='consumer_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='PSID'),
        ),
        migrations.AlterField(
            model_name='psidtracking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
