# Generated by Django 5.1.4 on 2025-01-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0044_paymentintimation_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintimation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='psidtracking',
            name='consumer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='psidtracking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='psidtracking',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
