# Generated by Django 5.1.4 on 2025-01-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0045_alter_paymentintimation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psidtracking',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='psidtracking',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='psidtracking',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psidtracking',
            name='paid_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psidtracking',
            name='payment_status',
            field=models.CharField(default='UNPAID', max_length=10),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='transaction_status_endpoint',
            field=models.URLField(blank=True, help_text='Transaction Status endpoint', null=True),
        ),
    ]
