# Generated by Django 5.1.4 on 2025-01-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0046_psidtracking_amount_paid_psidtracking_bank_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentIntimation',
        ),
    ]
