# Generated by Django 5.1.3 on 2025-01-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0043_merge_20241229_2201'),
        ('pmc_api', '0047_delete_paymentintimation'),
    ]

    operations = [
    ]
