# Generated by Django 5.1.4 on 2025-01-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0048_merge_20250104_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_for', models.CharField(default='producer', help_text='Type of license issued (e.g., Producer, Stockist, Distributor, etc.)', max_length=50, verbose_name='License For')),
                ('license_number', models.CharField(max_length=100, verbose_name='License Number')),
                ('license_duration', models.CharField(help_text="e.g., '3 Years'", max_length=50, verbose_name='License Duration')),
                ('owner_name', models.CharField(max_length=200, verbose_name='Owner’s Name')),
                ('business_name', models.CharField(max_length=200, verbose_name='Business Name')),
                ('types_of_plastics', models.CharField(help_text="e.g., 'ABC, DEF'", max_length=200, verbose_name='Types of Plastics')),
                ('particulars', models.CharField(help_text="e.g., 'ABC, DEF'", max_length=200, verbose_name='Particulars')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('date_of_issue', models.DateField(help_text="e.g., '10.01.2025'", verbose_name='Date of Issue')),
                ('applicant_id', models.IntegerField(help_text='Link this license to an applicant record', verbose_name='Applicant ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
