# Generated by Django 5.1.4 on 2025-01-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0050_license_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the license is active.', verbose_name='Is Active'),
        ),
    ]
