# Generated by Django 5.1.4 on 2025-02-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0051_license_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('violation_found', models.JSONField(blank=True, null=True)),
                ('violation_type', models.JSONField(blank=True, null=True)),
                ('action_taken', models.JSONField(blank=True, null=True)),
                ('plastic_bags_confiscation', models.FloatField(blank=True, null=True)),
                ('confiscation_other_plastics', models.JSONField(blank=True, null=True)),
                ('total_confiscation', models.FloatField(blank=True, null=True)),
                ('other_single_use_items', models.JSONField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
