# Generated by Django 5.1.4 on 2025-02-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0052_inspectionreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleUsePlasticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastic_items', models.JSONField(default=list)),
            ],
        ),
    ]
