# Generated by Django 5.1.4 on 2025-02-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0053_singleuseplasticssnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to='media/affidavits/'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='de_sealed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='fine_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='fine_recovery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='fine_recovery_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Recovered', 'Recovered')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='recovery_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
