# Generated by Django 5.1.4 on 2025-02-12 07:39

import pmc_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0055_inspectionreport_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to=pmc_api.models.upload_affidavits_to_with_uuid),
        ),
    ]
