# Generated by Django 5.1.6 on 2025-02-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0056_alter_inspectionreport_affidavit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetail',
            name='assigned_group',
            field=models.CharField(choices=[('APPLICANT', 'APPLICANT'), ('LSO', 'LSO'), ('LSO1', 'LSO1'), ('LSO2', 'LSO2'), ('LSO3', 'LSO3'), ('LSM', 'LSM'), ('DO', 'DO'), ('LSM2', 'LSM'), ('TL', 'TL'), ('DEO', 'DEO'), ('DG', 'DG'), ('Download License', 'Download License')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationassignment',
            name='assigned_group',
            field=models.CharField(choices=[('APPLICANT', 'APPLICANT'), ('LSO', 'LSO'), ('LSO1', 'LSO1'), ('LSO2', 'LSO2'), ('LSO3', 'LSO3'), ('LSM', 'LSM'), ('DO', 'DO'), ('LSM2', 'LSM'), ('TL', 'TL'), ('DEO', 'DEO'), ('DG', 'DG'), ('Download License', 'Download License')], max_length=100, null=True),
        ),
    ]
