# Generated by Django 5.1.6 on 2025-02-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0057_alter_applicantdetail_assigned_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='fine_recovery_breakup',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
