# Generated by Django 5.1.6 on 2025-02-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0059_alter_inspectionreport_district_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionreport',
            name='district',
        ),
    ]
