# Generated by Django 5.1.6 on 2025-02-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0060_remove_inspectionreport_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='district',
            field=models.ForeignKey(blank=True, db_column='district_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspectionreport', to='pmc_api.tbldistricts', verbose_name='District'),
        ),
    ]
