# Generated by Django 5.1.6 on 2025-02-24 09:28

import django.db.models.deletion
import pmc_api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0061_inspectionreport_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictPlasticCommitteeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('notification', 'Notification'), ('minutes', 'Minutes of Meeting')], max_length=50)),
                ('document', models.FileField(upload_to=pmc_api.models.upload_plastic_committee_to_with_uuid)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_documents', to='pmc_api.tbldistricts')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
