# Generated by Django 5.1.6 on 2025-02-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0062_districtplasticcommitteedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtplasticcommitteedocument',
            name='title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
