# Generated by Django 5.1.3 on 2025-04-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0068_accesslog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbldivisions',
            options={'managed': False, 'verbose_name_plural': 'Divisions'},
        ),
        migrations.AlterModelOptions(
            name='tbltehsils',
            options={'managed': False, 'ordering': ['tehsil_name'], 'verbose_name_plural': 'Tehsils'},
        ),
    ]
