# Generated by Django 5.1.6 on 2025-05-18 20:19

import django.utils.timezone
import pmc_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0069_alter_tbldivisions_options_alter_tbltehsils_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('institute', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('School', 'School/College'), ('University', 'University')], max_length=20)),
                ('competition_type', models.CharField(choices=[('poster', 'Poster'), ('painting', 'Painting'), ('3d_model', '3D Model')], max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('student_card_front', models.ImageField(upload_to=pmc_api.models.upload_student_card)),
                ('student_card_back', models.ImageField(blank=True, null=True, upload_to=pmc_api.models.upload_student_card)),
                ('registration_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
