# Generated by Django 5.1.6 on 2025-06-13 09:33

import pmc_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc_api', '0071_competitionregistration_photo_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinspectionreport',
            name='confiscation_receipt',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalinspectionreport',
            name='payment_challan',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalinspectionreport',
            name='receipt_book_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalinspectionreport',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='confiscation_receipt',
            field=models.FileField(blank=True, null=True, upload_to=pmc_api.models.upload_inspections_to_with_uuid),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='payment_challan',
            field=models.FileField(blank=True, null=True, upload_to=pmc_api.models.upload_inspections_to_with_uuid),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='receipt_book_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
