"""
Django settings for pmc_be project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

AUTHENTICATION_TOKEN_EXPIRY = timedelta(days=7)  # Example: Token expires in 7 days
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),  # Set desired access token lifetime
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Set desired refresh token lifetime
    # Additional settings can be configured here
}
windows_gdal_path = r'C:\\OSGeo4W\\bin\\'
if os.path.exists(windows_gdal_path):
    GDAL_LIBRARY_PATH = windows_gdal_path + 'gdal309'
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# MEDIA_ROOT = os.path.join(BASE_DIR, '/')
# MEDIA_URL = '/'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6d!d39lez)c@9(y6zz)bgmq6rv*i1^x74anmeu813cy3@z24_q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['plmis.epapunjab.pk',  # Your main domain
                 'www.plmis.epapunjab.pk',  # Subdomain (optional, for consistency)
                 '103.111.161.18',  # Public IP
                 '10.50.126.18',  # Private IP (optional, for internal communication)
                 '127.0.0.1',  # Localhost (for proxy forwarding)
                 'localhost',  # Localhost (for development/testing)
                 ]

# Application definition
#'oauth2_provider',

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'pmc_api.apps.PmcApiConfig',
    'pmc_be',
    'rest_framework_simplejwt',
    'oauth2_provider',
    'simple_history',
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'pmc_api.authentication.JWTAuthenticationWithUserTracking',  # ✅ must stay here
        'django_rest_token_expiry.authentication.ExpiringTokenAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pmc_api.middleware.CurrentUserMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]


ROOT_URLCONF = 'pmc_be.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pmc_be.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db2.sqlite3',
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'USER': '*****',
        'NAME': '*****',
        'HOST': '127.0.0.1',
        'PASSWORD': '*****',
        'PORT': '5432',
        'CONN_MAX_AGE': 600,  # 10 minutes
    }

}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, "static_root")
STATICFILES_DIRS = [os.path.join(PROJECT_ROOT, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/tmp/django_cache',
        'TIMEOUT': 3600,  # 1 hour
    }
}

SIMPLE_HISTORY_HISTORY_ID_USE_UUID = True  # optional, for cleaner IDs

SIMPLE_HISTORY_USER_ID_FIELD = 'user_id'  # default

# 👇 Add this so our `get_current_user()` is used
SIMPLE_HISTORY_GET_USER = 'pmc_api.middleware.get_current_user'